#' A Reference Class to generates differents model objects
#'
#' @description See the function blabla which produces an instance of this class
#' @importFrom R6 R6Class
#' This class comes with a set of methods, some of them being useful for the user:
#' See the documentation for blabla... Other methods
#'  should not be called as they are designed to be used during the optimization process.
#'
#' Fields should not be changed or manipulated by the user as they are updated internally
#' during the estimation process.
#' @field code a function which takes in entry X and theta
#' @field X the matrix of the forced variables
#' @field theta the vector of parameters to estimate
#' @field Yexp the experimental output
#' @field n the number of experiments
#' @field model the model choice see documentation
#' @seealso The function ....
model.class <- R6Class(classname = "model.class",
                 public = list(
                   code      = NULL,
                   X         = NULL,
                   Yexp      = NULL,
                   n         = NULL,
                   d         = NULL,
                   emul.list = NULL,
                   model     = NULL,
                   initialize = function(code=NA,X=NA,Yexp=NA,model=NA,
                                         emul.list=list(p=NA,PCA=NA,n.emul=NA))
                   {
                     self$code      <- code
                     self$X         <- X
                     self$Yexp      <- Yexp
                     self$n         <- length(Yexp)
                     self$d         <- dim(X)[2]
                     self$emul.list <- emul.list
                     self$model <- model
                     private$checkModels()
                   }
                 ))

model.class$set("private","checkModels",
        function()
        {
          if (self$model != "model1" & self$model != "model2" & self$model != "model3" & self$model != "model4")
          {
            stop('Please elect a correct model')
          }
        })

model1.class <- R6Class(classname = "model1.class",
                        inherit = model.class,
                        public=list(
                        initialize=function(code=NA, X=NA, Yexp=NA, model=NA)
                        {
                          super$initialize(code, X, Yexp, model)
                        },
                        fun = function(theta,sig2)
                        {
                          return(self$code(self$X,theta)+rnorm(self$n,0,sqrt(sig2)))
                        })
                        )

model2.class <- R6Class(classname = "model2.class",
                        inherit = model.class,
                        public = list(
                          n.emul = NULL,
                          GP     = NULL,
                          p      = NULL,
                          binf   = NULL,
                          bsup   = NULL,
                          PCA    = NULL,
                        initialize = function(code=NA, X=NA, Yexp=NA, model=NA,opt.emul=NA)
                        {
                          super$initialize(code, X, Yexp, model)
                          self$binf   <- opt.emul$binf
                          self$bsup   <- opt.emul$bsup
                          self$n.emul <- opt.emul$n.emul
                          self$p      <- opt.emul$p
                          self$PCA    <- opt.emul$PCA
                          self$GP     <- self$surrogate()
                          print("The surrogate has been set up, you can now use the function")
                        },
                        surrogate = function()
                        {
                          Xcr <- scale(X)
                          V   <- attr(Xcr,"scaled:scale")
                          M   <- attr(Xcr,"scaled:center")
                          Dim <- self$p+self$d
                          if (self$PCA==TRUE)
                          {
                            D <- self$PCA.fun(X=self$X,Dim=Dim,n=self$n.emul,p=self$p,d=self$d,
                                              binf=self$binf,bsup=self$bsup,M=M,V=V)
                            print(D)
                          } else
                          {
                            doe <- lhsDesign(self$n.emul,Dim)$design
                            doe <- maximinSA_LHS(doe)
                            doe <- doe$design
                            ### Getting back the value of the parameter generated by the DOE
                            binf.X <- apply(Xcr,2,min)
                            bsup.X <- apply(Xcr,2,max)
                            DOE <- unscale(doe[,1:self$d],binf.X,bsup.X)
                            for (i in 1:self$d)
                            {
                              DOE[,i] <- DOE[,i]*V[i]+rep(M[i],self$n.emul)
                            }
                            doeParam <- unscale(doe[,(Dim-self$p+1):Dim],self$binf,self$bsup)
                            ### Matrix D contains the final value for the DOE
                            D <- cbind(DOE,doeParam)
                          }
                          ### Generating the response
                          z <- self$code(D[,1:(Dim-self$p)],D[,(Dim-self$p+1):Dim])
                          ### Converting D as a data.frame for the km function
                          D <- as.data.frame(D)
                          #colnames(D) <- c("V1","V2","V3","V4","V5","V6")
                          ### Creation of the Gaussian Process with estimation of hyperpameters
                          GP <- km(formula =~1, design=D, response = z,covtype = "matern5_2")
                          return(GP)
                        },
                        fun = function(theta,sig2)
                        {
                          options(warn=-1)
                          if(self$p==1)
                          {
                            Xnew <- cbind(X,rep(theta,self$n))
                          } else
                          {
                            Xtemp <- matrix(rep(theta,c(self$n,self$n)),nr=self$n,nc=self$p)
                            Xnew  <- cbind(X,Xtemp)
                          }
                          pr <- predict(self$GP,newdata=Xnew,type="UK",cov.compute=TRUE)
                          err <- rnorm(n=self$n,mean = 0,sd=sqrt(sig2))
                          return(list(y=pr$mean+err,Cov.GP=pr$cov))
                        })
                        )


model2.class$set("public","PCA.fun",
                function(X,Dim,n,p,d,binf,bsup,M,V)
                {
                  PCA.sim <- PCA(X,graph = FALSE)
                  ### Coordinates in the new uncorrelated space of the initial points
                  B <- PCA.sim$ind$coord
                  ### Transition matrix
                  P <- sqrt(PCA.sim$var$contrib[,1:d])/10 * sign(PCA.sim$var$coord[,1:d])
                  ### Establishment of the DOE
                  doe <- lhsDesign(n,Dim)$design
                  doe <- maximinSA_LHS(doe)
                  doe <- doe$design
                  ### Boundaries of the points in the new coordinates
                  binf.X <- apply(B,2,min)
                  bsup.X <- apply(B,2,max)
                  ### Unscaling the doe into the right bounds
                  DOE <- unscale(doe[,1:d],binf.X,bsup.X)
                  ### Matrix containing the points from the DOE but in the initial coordinates
                  A <- t(P%*%t(DOE))
                  ### Multiplication of each components by the variance and add the mean
                  for (i in 1:d)
                  {
                    A[,i] <- A[,i]*V[i]+rep(M[i],n)
                  }
                  ### Getting back the value of the parameter generated by the DOE
                  doeParam <- unscale(doe[,(Dim-p+1):Dim],binf,bsup)
                  ### Matrix D contains the final value for the DOE
                  D <- cbind(A,doeParam)
                  return(D)
                })

model3.class <- R6Class(classname = "model3.class",
                        inherit = model1.class,
                        public=list(
                          funC = NULL,
                          initialize=function(code=NA, X=NA, Yexp=NA, model=NA)
                          {
                            super$initialize(code, X, Yexp, model)
                            self$funC <- super$fun
                          },
                          discrepancy = function(theta,thetaD,sig2)
                          {
                            Yc    <- self$funC(theta,sig2)
                            z     <- self$Yexp - Yc$y
                            emul  <- km(formula=~1, design=as.data.frame(self$X), response=z,coef.trend=0,
                                    coef.var = thetaD[1], coef.cov = rep(thetaD[2],ncol(self$X)),
                                    covtype="gauss", scaling = FALSE)
                            biais <- simulate(object=emul, nsim=1, seed=NULL, cond=FALSE,
                                              nugget.sim=0,checkNames=FALSE)
                            return(list(biais=biais,Yc=Yc))
                          },
                          fun = function(theta,thetaD,sig2)
                          {
                            res <- self$discrepancy(theta,thetaD,sig2)
                            return(res$biais+res$Yc)
                          }
                          )
)


model4.class <- R6Class(classname = "model4.class",
                        inherit = model2.class,
                        public=list(
                          funC = NULL,
                          initialize=function(code=NA, X=NA, Yexp=NA, model=NA,opt.emul=NA)
                          {
                            super$initialize(code, X, Yexp, model,opt.emul)
                            self$funC <- super$fun
                          },
                          discrepancy = function(theta,thetaD,sig2)
                          {
                            Yc    <- self$funC(theta,sig2)
                            z     <- self$Yexp - Yc
                            emul  <- km(formula=~1, design=as.data.frame(self$X), response=z,coef.trend=0,
                                        coef.var = thetaD[1], coef.cov = rep(thetaD[2],ncol(self$X)),
                                        covtype="gauss", scaling = FALSE)
                            biais <- simulate(object=emul, nsim=1, seed=NULL, cond=FALSE,
                                              nugget.sim=0,checkNames=FALSE)
                            return(list(biais=biais,Yc=Yc))
                          },
                          fun = function(theta,thetaD,sig2)
                          {
                            res <- self$discrepancy(theta,thetaD,sig2)
                            return(res$biais+res$Yc)
                          })
)



