# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MetropolisHastingsCpp <- function(Ngibbs, Nmh, theta_init, k, SIGMA, Yf, binf, bsup, LogTest, stream) {
    .Call('_calibrationCode_MetropolisHastingsCpp', PACKAGE = 'calibrationCode', Ngibbs, Nmh, theta_init, k, SIGMA, Yf, binf, bsup, LogTest, stream)
}

invMat <- function(V) {
    .Call('_calibrationCode_invMat', PACKAGE = 'calibrationCode', V)
}

FlushCPP <- function() {
    invisible(.Call('_calibrationCode_FlushCPP', PACKAGE = 'calibrationCode'))
}

MetropolisHastingsCppD <- function(Ngibbs, Nmh, theta_init, k, SIGMA, Yf, binf, bsup, LogTest, stream) {
    .Call('_calibrationCode_MetropolisHastingsCppD', PACKAGE = 'calibrationCode', Ngibbs, Nmh, theta_init, k, SIGMA, Yf, binf, bsup, LogTest, stream)
}

