# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MetropolisHastingsCpp <- function(model, Ngibbs, Nmh, theta_init, k, SIGMA, Yf, binf, bsup, LogTest) {
    .Call('_calibrationCode_MetropolisHastingsCpp', PACKAGE = 'calibrationCode', model, Ngibbs, Nmh, theta_init, k, SIGMA, Yf, binf, bsup, LogTest)
}

invMat <- function(V) {
    .Call('_calibrationCode_invMat', PACKAGE = 'calibrationCode', V)
}

